language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: vkybngQTa5ScXbPZavPl0OXx5eLR4K6Putk1pTi/3PYMQ+WRKpvOFmPsmB+qN9QQ1GcmYYyH0ZCFSNz2h//2Sco3OoxHZanXT7voNQLRm8CRQkR4NgdvK1/wkOJijHZrCLlCoxc50soIfVQYaQCiUTFI3DXWVVXL7zXjOOr6Hy8I26P+HJGo1eCvVhUt55RWLTNLqghNSRrDG844s5gvIWU9v0+iOO3dfEmIcaM6JRvUe44FQRiqi6cW35YVlEc29eydVyGP9oM2mEHiGZ4W9Ql4Oewczn7N009qivBYwJyjzMjeqjw+OiUYiP3xVHLJbUEM6AQg7WGaBXD/QWNgwWSRbVk6CsLL8tUN/vUM0YaVIOOsq+pVk2DvlCqStByYnabEck+LYk+RknzQKRISkITDMUSVtwNPt1uqfMS/jijftcS0RJ7/+BsHq+kg9YPbwwhvD4WGjUWHYkShqfbyihFyUdO0XgeT4FJ7QvBxrKwda3xmrpzW7OG8dccNBkA3tzU7uSENuf43XTxR2kyKSYmUXY+lI51YS9TSlmtXugYh/ff9xeURbiZAG4vLAqHR7bi76uB1XQqch2dElv1QyJKIaMN5mGuqM01xUoEynRQLL9cB+oY/WlkrxQT+HK00YA+R/7akOc8vou6WNPPXktvNnemOIgYeTmBift6NKzQ=
  app:
    development: sesews2015
