language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: A0s/i3bkDN0nvPzH8g2+sJQmtxYPa1vWIrAWl14N+juYuzBfi+3yw4lmlXtsfAYtOP0rT6OxxM90/wmDbR7g3c0NClUHF8vwAsNCO+ifx5sLmSADXa2nAUgm80XjrqeIGiEsY5FweeiY/bDlMIUkRsFv+EdPDFo7buNyIZU+cTNCMJ9amgHTqenuXobx8suzA1Qpj7Eg6AeJxr9Gqg1WZ3sLiyXh2FKDLywY5XpNhzI0LdFBM6cl11SgTb5dZjE5qMqS9zIjCFo+RC/YE1j8tp98BF3OV0ZTTkeAslbBv6hbZc+oHpbQALGMC8SHXJ302eEl9jT6PU0UWtEUQ6gPmAOoO0O/gF3DNjWSqj+M459jZP9JeZGBNycYRwz0ET+h/ikV92E5q18+VQLMGuGWqqPa4d4je9u3Joi3C0QVrH1+TaN+i/73MEhoYuEK7ayQ1UUe9DX0PI9yUSLYUOmuFOsyawhZAqilX0SvWt8Wl7V653DbW7G1/3uS0OBhnCk/mB/hyiemccdvvl2n+XdNssm/augIaOmqYIliW1Yo2iemVKYxFFfETliowxRKY/ruS5tWCA5ZhLf16NAjnZ6YJYkyIr9nqj7xcQ6rcT/E7/dT8iJFKXbqFxdqboSJAFXFWWZqfLYC30YXXg1R1DZiWQuaSg41wYpfkLA6+tiqZTk=
  app:
    development: testsese
